# See also config/config_environment_specific.yml

javascripts:
  - 'http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'
  - 'jquery.uniform.min'
  - 'jquery.isotope.min'
  - 'rails'
  - 'application' # This should be last

pagination:
  per_page: 50