# See also config/config_environment_specific.yml

javascripts:
  - 'https://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js'
  # - 'jquery.min'
  - 'jquery.uniform.min'
  - 'rails'
  - 'application' # This should be last

pagination:
  per_page: 50