development:
  adapter: mysql2
  encoding: utf8
  database: sniph_development
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: sniph_test
  username: root
  password:

cucumber:
  <<: *test
